### ISSUE TITLE
Suggestion: Add a config setting to change orbital launcher working dimension

### ISSUE THREAD

**Issue by tooopt** [Bax12/dysonsphere#1]
Currently the mod only allows to use orbital launcher in the overworld, and attempting to use it in other dimension does not work. I was making a modpack and wanted orbital launcher to work only in ad astra's Mercury dimension, but it appears that it is not possible to change the dimension via config or via datapacks. 

Same thing with Dyson Sphere observer and Dyson sphere energy reciever. Option to change or add more dimensions where all these machines could work would be nice.

![2024-07-04_09 44 14](https://github.com/Bax12/dysonsphere/assets/139614444/967261fc-8774-4530-84d6-cc1735322f68)

**Comment by Bax12** [comment]
I like the idea, my plan would be to share the same Dyson Sphere between the dimensions.
As with e.g. ad astra's dimensions there would only be one sun for all of them.

The nether and the end should still be blacklisted, but I think there should be no problem to add a config value for a dimension black-/whitelist once the initial sharing across dimensions is implemented.

I'll look into it.

**Comment by Bax12** [comment]
I pushed a new version with a dimension config to modrinth and curseforge.
Please let me know if there are any issues with it.

**Comment by tooopt** [comment]
Thank you! This is exactly what I wanted! I tested the config file really quick, white list, and a bunch of dimensions. So far everything works perfectly. Thanks!
