### ISSUE TITLE
[Backport Request] -- 1.19.2

### ISSUE THREAD

**Issue by weirdspecter** [Bax12/dysonsphere#2]
Hi there.

Dyson Sphere Program seems incredibly well suited for my modded game and... frankly, just incredible, but is unfortunately only available for 1.20.1. While I recognise that the time and effort involved in porting a mod across versions of Minecraft (and likely Forge) is substantial, I'd like to request that this mod be backported to 1.19.2.

Thank you for any and all consideration.

**Comment by Bax12** [comment]
The short answer: no

The longer answer:
In a perfect world we could just slap mods together without caring for specific versions of the game or loaders. But sadly we have to deal with different version that in part change little things and in part overthrow entire systems. Maintaining two different version of the mod for two different versions of the game is not trivial enough to be solved by an automated workflow, as far as I know. Leading to the worst case of coding the same features twice.
As I still have a few ideas I want to implement before calling it a 1.0 or even finished I don't intend to spread my limited time for the project even thinner. Once I am done with my current plans I can look into moving to a different version. This direction will however most certainly be up.
If you, or anyone for that matter, want to (back) port the mod to a different version: Go ahead! That's what open source is about. While I will try to help in such an endeavor it would not be my project and I wont make promises that I can't keep.

 Thank you for your interest in my project, I hope you can understand my standpoint.
